# Lazygit configuration
gui:
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
    defaultFgColor:
      - white
  showIcons: true
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  parseEmoji: true
os:
  editCommand: 'nvim'
